# Apply Machine Learning Algorithms over Sample Data 

### fei.zhang@ga.gov.au
### June 2016

In [1]:
import os, sys
import pickle
import numpy as np

from numpy import genfromtxt

import pandas as pd
#import pandas.io.data
from pandas_datareader import data, wb
from pandas import DataFrame



%matplotlib inline
import matplotlib.pyplot as plt
from pylab import rcParams
rcParams['figure.figsize'] = 10, 10 # increase plot size a bit...
rcParams['axes.formatter.useoffset'] = False  # disable scalar formatter / offset in axes labels

In [10]:
# import your own modules by providing path
sys.path.append('../python')

import apply_detree

#import imp; imp.reload(apply_detree)  # force the interpreter to re-import if apply_detree.py changed

In [8]:
!ls -l /g/data/ha3/fxz547/Githubz/SUMMAR.CSV
#my_file_csv='/g/data/u46/fxz547/wofs_training_sample_data/orig_copy/Test_Tile_samples_20140203.csv'


-rw-r--r-- 1 fxz547 ha3 1638229394 Mar 14  2018 /g/data/ha3/fxz547/Githubz/SUMMAR.CSV


In [11]:
my_file_csv='/g/data/ha3/fxz547/Githubz/SUMMAR.CSV'
pdf = apply_detree.get_pdf_from_csv(my_file_csv)
# todo: keep the old class_label. how to add a new_class column?

/g/data1a/ha3/fxz547/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2901: DtypeWarning: Columns (0,2,3,4,5,6,7,8,10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):


In [12]:
pdf.shape

(4572697, 12)

In [13]:
#  Assign W_* into Water; all other classes into NotWater. Binary classes

pdf['myclass'] = 0 # add a new column myclass
# change the column myclass to datatype uint8
pdf[['myclass']] =pdf[['myclass']].astype('uint8')

w_condition= pdf.Class_name.str.startswith('W') | pdf.Class_name.str.endswith('_Water')  #match('^W_*') and CloudShadow_Water

pdf.loc[w_condition, 'myclass'] = 128 #'Water'


In [14]:
# df[['id']] = df[['id']].astype(int)

pdf.dtypes

Bright        object
Class_name    object
Mean_PQMas    object
Mean_tm1c     object
Mean_tm2c     object
Mean_tm3c     object
Mean_tm4c     object
Mean_tm5c     object
Mean_tm7c     object
Scene_Name    object
X_Min_Pxl     object
Y_Min_Pxl     object
myclass        uint8
dtype: object

In [15]:
pdf['myclass'].dtypes

dtype('uint8')

In [16]:
# Group by Pixel Class_name, then count the number of rows in each group
pdf.groupby('myclass').count()

Bright  Class_name  Mean_PQMas  Mean_tm1c  Mean_tm2c  Mean_tm3c  \
myclass                                                                     
0        3753600     3753600     3753600    3753600    3753600    3753600   
128       819097      819097      819097     819097     819097     819097   

         Mean_tm4c  Mean_tm5c  Mean_tm7c  Scene_Name  X_Min_Pxl  Y_Min_Pxl  
myclass                                                                     
0          3753600    3753600    3753600     3753600    3753600    3753600  
128         819097     819097     819097      819097     819097     819097

In [17]:
pdf.groupby('Mean_PQMas').count()  # perfect good pixels

Bright  Class_name  Mean_tm1c  Mean_tm2c  Mean_tm3c  Mean_tm4c  \
Mean_PQMas                                                                    
16383.0     4572697     4572697    4572697    4572697    4572697    4572697   

            Mean_tm5c  Mean_tm7c  Scene_Name  X_Min_Pxl  Y_Min_Pxl  myclass  
Mean_PQMas                                                                   
16383.0       4572697    4572697     4572697    4572697    4572697  4572697

In [18]:
pdf.groupby('Class_name').count()

Bright  Mean_PQMas  Mean_tm1c  Mean_tm2c  Mean_tm3c  \
Class_name                                                                 
Bare                 784802      784802     784802     784802     784802   
BldShadow              5332        5332       5332       5332       5332   
CloudShadow_Bare      34395       34395      34395      34395      34395   
CloudShadow_Veg       29516       29516      29516      29516      29516   
CloudShadow_Water       651         651        651        651        651   
Cropping_Bare        107755      107755     107755     107755     107755   
Cropping_DenseVeg     60621       60621      60621      60621      60621   
Dark_Soil             75623       75623      75623      75623      75623   
Road                  10405       10405      10405      10405      10405   
Salt                  35467       35467      35467      35467      35467   
Snow                  29843       29843      29843      29843      29843   
TerrainShadow_Bare   378545      378545     378545     378545     378545   
TerrainShadow_Snow     7702        7702       7702       7702       7702   
TerrainShadow_Veg    155010      155010     155010     155010     155010   
V_Forest            1010696     1010696    1010696    1010696    1010696   
V_Grassland          940233      940233     940233     940233     940233   
V_Riparian            87655       87655      87655      87655      87655   
W_Dark                45764       45764      45764      45764      45764   
W_Estuary             70229       70229      70229      70229      70229   
W_LargeBody          224292      224292     224292     224292     224292   
W_River               41887       41887      41887      41887      41887   
W_SalineFlats          7618        7618       7618       7618       7618   
W_Salt_Lake          117331      117331     117331     117331     117331   
W_Sea                  2435        2435       2435       2435       2435   
W_SmallBody           50244       50244      50244      50244      50244   
W_Swamp               60883       60883      60883      60883      60883   
W_Turbid             185642      185642     185642     185642     185642   
W_VegMix              12121       12121      12121      12121      12121   

                    Mean_tm4c  Mean_tm5c  Mean_tm7c  Scene_Name  X_Min_Pxl  \
Class_name                                                                   
Bare                   784802     784802     784802      784802     784802   
BldShadow                5332       5332       5332        5332       5332   
CloudShadow_Bare        34395      34395      34395       34395      34395   
CloudShadow_Veg         29516      29516      29516       29516      29516   
CloudShadow_Water         651        651        651         651        651   
Cropping_Bare          107755     107755     107755      107755     107755   
Cropping_DenseVeg       60621      60621      60621       60621      60621   
Dark_Soil               75623      75623      75623       75623      75623   
Road                    10405      10405      10405       10405      10405   
Salt                    35467      35467      35467       35467      35467   
Snow                    29843      29843      29843       29843      29843   
TerrainShadow_Bare     378545     378545     378545      378545     378545   
TerrainShadow_Snow       7702       7702       7702        7702       7702   
TerrainShadow_Veg      155010     155010     155010      155010     155010   
V_Forest              1010696    1010696    1010696     1010696    1010696   
V_Grassland            940233     940233     940233      940233     940233   
V_Riparian              87655      87655      87655       87655      87655   
W_Dark                  45764      45764      45764       45764      45764   
W_Estuary               70229      70229      70229       70229      70229   
W_LargeBody            224292     224292     224292      224292     224292   
W_River                 

In [19]:
#perfect pixel has a quality flag 13683 in the column Mean_PQMa
bin(16383)

'0b11111111111111'

In [20]:
df_wlargebody= pdf[pdf['Class_name'] =='W_LargeBody']
df_wlargebody.shape

(224292, 13)

# Separate the Water and NonWater data

In [21]:
dfwater=pdf[pdf['myclass'] ==128]
dfnowater= pdf[pdf['myclass'] == 0]

In [22]:
dfwater.shape

(819097, 13)

In [23]:
dfnowater.shape

(3753600, 13)

# Plotting the values

See http://pandas.pydata.org/pandas-docs/stable/visualization.html


# How to design best ML models accordingly?

In [19]:
# https://www.google.com.au/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=how+to+design+Machine+learning+models+according+feature+stats

## Prepare sample dataset for scikit analysis

In [25]:
clm_list = []
for column in pdf.columns: clm_list.append(column)
    
print (clm_list)

['Bright', 'Class_name', 'Mean_PQMas', 'Mean_tm1c', 'Mean_tm2c', 'Mean_tm3c', 'Mean_tm4c', 'Mean_tm5c', 'Mean_tm7c', 'Scene_Name', 'X_Min_Pxl', 'Y_Min_Pxl', 'myclass']


In [26]:
# select 3 most important feature attributes as predictive columns
# Note that the order of these variables does not matter. The same decision tree will be arrived
pred_cols= [ clm_list[10],clm_list[12], clm_list[6], clm_list[7]]
print(pred_cols)

['X_Min_Pxl', 'myclass', 'Mean_tm4c', 'Mean_tm5c']


In [28]:
#select the columns values into numpy array

X= pdf[pred_cols].values

Y = pdf['myclass'].values  # the new column myclass
       
print (X.shape, type(X), X.dtype)
print (Y.shape, Y.dtype)

(4572697, 4) <class 'numpy.ndarray'> object
(4572697,) uint8


In [22]:
X[:2]

array([[  3.16631872e-01,   6.74264008e-02,   8.22000000e+02,
          9.46000000e+02],
       [  3.95655036e-01,   1.28205128e-01,   8.56000000e+02,
          1.06000000e+03]])

In [29]:
Xw = dfwater[pred_cols].values

In [30]:
Xw[:2]

array([[3104.0, 128, 1193.0, 558.0],
       [3131.0, 128, 2236.0, 535.0]], dtype=object)

## Scikit-learn

In [31]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(max_depth=7)

# Traing the model with the sample data %time clf = clf.fit(X, Y)

clf = clf.fit(X, Y)

In [32]:
# verify the model using function predict
isample= 227014
# Or get a random sample to compare
#isample=np.random.random_integers(0,999)

print (isample, clf.predict(X[isample,:].reshape(1, -1) ), Y[isample], pdf.Class_name.iloc[isample])

227014 [128] 128 W_Dark


In [33]:
#3) Apply / evaluate
clf.score(X,Y)

1.0

In [38]:
# new import sklearn.model_selection
#ModuleNotFoundError: No module named 'sklearn.cross_validation'

In [36]:
# Advanced_sklearn/Chapter%201/Classification.ipynb
# more methods, split the samples , validation  
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y)

In [39]:
print (X_test.shape)
clf.score(X_test,y_test)


(1143175, 4)


1.0

In [41]:
# Cross validation
from sklearn.model_selection import cross_val_score

for classifier in [clf] :
    scores = cross_val_score(classifier, X, Y, cv=5)
    print(scores)
    print(np.mean(scores))

[1. 1. 1. 1. 1.]
1.0


In [42]:
# Let's Generate the Tree.

from IPython.display import Image 
from sklearn.externals.six import StringIO  
import pydot 
with open("de_tree.dot", 'w') as f: f = tree.export_graphviz(clf, out_file=f)

    
# dot -Tpdf iris.dot -o iris.pdf

!dot -Tpdf de_tree.dot -o de_tree4v7Dep.pdf

ModuleNotFoundError: No module named 'pydot'

In [36]:
# http://scikit-learn.org/stable/modules/model_persistence.html
import pickle
s = pickle.dumps(clf)

#print(s)
#to unpickle clf2 = pickle.loads(s)
#clf2.predict(X[0:1])
#array([0])


In [43]:
# unpickle
clf1 = pickle.loads(s)

NameError: name 's' is not defined

In [38]:
from sklearn.externals import joblib
joblib.dump(clf, 'detreedep5.pkl') 

#Later you can load back the pickled model (possibly in another Python process) with:
#clf = joblib.load('detreedep5.pkl')

# Note joblib.dump returns a list of filenames. Each individual numpy array contained in the clf object is serialized as a separate file on the filesystem. All files are required in the same folder when reloading the model with joblib.load.

['detreedep5.pkl',
 'detreedep5.pkl_01.npy',
 'detreedep5.pkl_02.npy',
 'detreedep5.pkl_03.npy',
 'detreedep5.pkl_04.npy']

In [39]:
clf2 = joblib.load('detreedep5.pkl')

In [40]:
with open('detree_clf.pickle', 'wb') as f:
    # Pickle the 'data' dictionary using the highest protocol available.
    pickle.dump(clf, f, pickle.HIGHEST_PROTOCOL)

In [41]:

with open('detree_clf.pickle', 'rb') as f:
    # The protocol version used is detected automatically, so we do not
    # have to specify it.
    clf3 = pickle.load(f)

In [42]:
print (clf,clf1,clf2,clf3)

(DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best'), DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best'), DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best'), DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_w

In [43]:
if clf2 ==clf1:  # This object comparison does not work correctly
    print ("unpickled OK")
else:
    print("This may not worked?")

This may not worked?


In [44]:
isample= 104971

print (isample, clf.predict(X[isample,:].reshape(1, -1) ), Y[isample], pdf.Class_name.iloc[isample])

print (isample, clf1.predict(X[isample,:].reshape(1, -1) ), Y[isample], pdf.Class_name.iloc[isample])
print (isample, clf2.predict(X[isample,:].reshape(1, -1) ), Y[isample], pdf.Class_name.iloc[isample])
print (isample, clf3.predict(X[isample,:].reshape(1, -1) ), Y[isample], pdf.Class_name.iloc[isample])

(104971, array([128], dtype=uint8), 128, 'W_SalineFlats')
(104971, array([128], dtype=uint8), 128, 'W_SalineFlats')
(104971, array([128], dtype=uint8), 128, 'W_SalineFlats')
(104971, array([128], dtype=uint8), 128, 'W_SalineFlats')


# Google search how to select important feature

** http://machinelearningmastery.com/an-introduction-to-feature-selection/

** http://scikit-learn.org/stable/modules/feature_selection.html
    

# you can pickle the clf tree for later use.

In [44]:
# http://scikit-learn.org/stable/modules/model_persistence.html

# http://stackoverflow.com/questions/15564410/scikit-learn-svm-how-to-save-load-support-vectors
# 
# show tree

clf.tree_.__getstate__()['nodes']

array([( 1,  2,  1, 64., 0.29408202, 4572697, 4572697.),
       (-1, -1, -2, -2., 0.        , 3753600, 3753600.),
       (-1, -1, -2, -2., 0.        ,  819097,  819097.)],
      dtype=[('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')])

# Let's Try some other methods

In [46]:
# from sklearn.svm import LinearSVC
# svm = LinearSVC(C=0.1)
# svm.fit(X_train, y_train)


# print(svm.predict(X_train))
# print(y_train)

# svm.score(X_train, y_train)

# svm.score(X_test, y_test)

# Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50)
rf.fit(X_train, y_train)
rf.predict(X_test)

rf.score(X_test, y_test)


In [49]:
from sklearn.svm import LinearSVC
svm = LinearSVC(C=0.1)
svm.fit(X_train, y_train)


print(svm.predict(X_train))
print(y_train)

# svm.score(X_train, y_train)

svm.score(X_test, y_test)


#Stop here. Do acuracy comparison:
    
# Random Forest 99.310%  Train slow
# LinearSVM 90.799%
# DecisionTree(depth=7) 96.756%  Train very fast. Complex tree

/home/547/fxz547/.local/lib/python3.6/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[  0 128 128 ...   0 128   0]
[  0 128 128 ...   0 128   0]


0.9999991252432917

# Cross Validation
Advanced_sklearn/Chapter%201/Cross%20Validation.ipynb

In [50]:
# compute resource limit problem 
from sklearn.model_selection import cross_val_score

#for classifier in [clf, svm, rf]:
for classifier in [clf] :
    scores = cross_val_score(classifier, X, Y, cv=5)
    print(scores)
    print(np.mean(scores))

# Results with my_file_csv='/g/data/u46/fxz547/wofs_training_sample_data/orig_copy/Test_Tile_samples_20140203.csv'
# random forest is no better than clf. svm is no good.
# [ 0.93761947  0.9168854   0.93080083  0.96054265  0.97094193]
# cls:  0.943358053934
# [ 0.84295027  0.93209894  0.90567316  0.90808262  0.90809689]
# svm:  0.899380377677
# [ 0.92633591  0.91465293  0.94864626  0.94893796  0.97848818]
# rf: 0.943412249083

[1. 1. 1. 1. 1.]
1.0


In [51]:
!ls -ltr

total 3740
-rw-r--r-- 1 fxz547 ha3  49657 Jun  4 15:04 visualize_geotiff_files.ipynb
-rw-r--r-- 1 fxz547 ha3  99687 Jun  4 15:04 NCI_Training_GA_Jan2016.ipynb
-rwxr-xr-x 1 fxz547 ha3 618344 Jun  4 15:04 machine_Learn_water_data.ipynb
-rw-r--r-- 1 fxz547 ha3  22037 Jun  4 15:04 feature_selection_howto.ipynb
-rw-r--r-- 1 fxz547 ha3 482913 Jun  4 15:04 explore_water_datas.ipynb
-rw-r--r-- 1 fxz547 ha3 566670 Jun  4 15:04 explore_sample_data_for_water_v2.ipynb
-rw-r--r-- 1 fxz547 ha3 622030 Jun  4 15:04 explore_sample_data_for_water.ipynb
-rw-r--r-- 1 fxz547 ha3  76691 Jun  4 15:04 explore_netcdf_stack_tile.ipynb
-rwxr-xr-x 1 fxz547 ha3  88626 Jun  4 15:04 explore_csv_data.ipynb
-rwxr-xr-x 1 fxz547 ha3 216462 Jun  4 15:04 analyse_water_yearlysummary_csv2.ipynb
-rw-r--r-- 1 fxz547 ha3 277370 Jun  4 15:04 analyse_water_yearlysummary_csv1.ipynb
-rw-r--r-- 1 fxz547 ha3  27998 Jun  4 15:14 water_pixel_images_classif.ipynb
-rw-r--r-- 1 fxz547 ha3 608373 Jun  4 16:01 machine_Learn_water_pixel_csv

NameError: name 'clf3' is not defined

## Select Data to Analyse 